name: rgenerator
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - camelot-py
  - matplotlib
  - numpy
  - pandas
  - pillow
  - requests
  - tqdm
  - xlrd
  - fastapi
  - uvicorn
  - pip
  - pytest
  - pytest-cov
  # miktex: instalar manualmente según SO
  # Windows: https://miktex.org/download
  # Linux: sudo apt install texlive-full
  - git
  - streamlit
  - ipykernel
  - pip:
      - openpyxl
      - pymupdf
      - docxtpl
      - docx2pdf
      - python-dotenv
      - sqlalchemy
      - psycopg2-binary
      - bcrypt
      - python-jose[cryptography]
      - passlib[bcrypt]
      - python-multipart
      - "-e ."